openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8989'
    description: Generated server url
paths:
  /oauth2/token:
    post:
      tags:
        - token-controller
      summary: 'The API creates a token for a user and supports the following grant types: device_token and refresh_token.'
      operationId: token
      parameters:
        - name: Authorization
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: X-Device-FingerPrint
          in: header
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: scope
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokeRequestDto'
      responses:
        '200':
          description: Returns the single DTO object for all grant types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDto'
        '400':
          description: 'Returns bad request for the following cases: invalid or expired refresh token (type: ''invalid_grant'')'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '401':
          description: 'Returns Unauthorized status if the second factor is required (type: ''second_factor_required'')'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '403':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '500':
          description: 'Unknow error (type: ''generic_error'')'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
  /oidc/logout:
    get:
      tags:
        - token-controller
      operationId: logout
      parameters:
        - name: id_token_hint
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: default response
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '401':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '403':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
components:
  schemas:
    ErrorDto:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
        additional_properties:
          type: object
          additionalProperties:
            type: string
    TokenDto:
      type: object
      properties:
        scope:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        id_token:
          type: string
    TokeRequestDto:
      required:
        - grant_type
      type: object
      properties:
        secureCode:
          type: string
        challenge:
          type: string
        deviceTokenID:
          type: string
        sessionDataKey:
          type: string
        scope:
          type: string
        transactionId:
          type: string
        unk:
          type: string
        eventBasedOTP:
          type: string
        otp:
          type: string
        biometry:
          type: boolean
        grant_type:
          type: string
          description: 'The field describe the behavior of action, The following values illustrate of available behaviors: device_token use for create token, refresh_token use for update token '
          enum:
            - device_token
            - refresh_token
        refresh_token:
          type: string
          description: The field is required if specified refresh_token grant type
