openapi: 3.0.0
info:
  title: id-vtb-ru
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /oauth2/ac:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: ''
    post:
      summary: OAUTH2 аутентификация с доп параметрами
      description: ''
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: ../models/individual.v1.yaml
        description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: scope
          description: 'разрешения, позволяющие провести аутентификацию (openid) и получить данные о пользователе '
          required: true
        - schema:
            type: string
          in: query
          name: response_type
          description: 'параметр, определяющий, что мы хотим получить авторизационный код'
          required: true
        - schema:
            type: string
          in: query
          name: redirect_uri
          description: 'адрес, на который должен быть возвращен пользователь после проведения аутентификации (URL encoded)'
          required: true
        - schema:
            type: string
          in: query
          name: state
          description: набор случайных символов
          required: true
        - schema:
            type: string
          in: query
          name: client_id
          description: 'идентификатор вас как партнера ВТБ ID, заданный в параметрах приложеия'
          required: true
        - schema:
            type: string
            enum:
              - login
              - ucn
              - phone
              - cardnumber
          in: query
          name: auth_by
          description: ''
        - schema:
            type: string
          in: query
          name: auth_value
      responses:
        '302':
          description: Переход на страницу второго фактора
components:
  schemas: {}
