openapi: 3.0.1
info:
  title: SSOAPI definition
  version: v0
  contact:
    name: Artem Ivlev
  description: Апи входа
servers:
  - url: 'http://localhost:8989'
    description: Generated server url
paths:
  /oauth2/token:
    post:
      tags:
        - token-controller
      operationId: getToken
      parameters:
        - name: X-Device-FingerPrint
          description: base64 упакованный JSON объект описания устройства с которого пользователь входит. Данные получаются из библиотеки
          in: header
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: scope
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Всё хорошо - получите объект с токенами
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDto'
        '400':
          description: 'Ошибка токена, например, refresh токен уже протух'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '401':
          description: 'Ошибка входа, например, нужен второй фактор'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '403':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '500':
          description: "Unknow error (type: 'generic_error')"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDto'
      description: Получение токена
      security:
        - service-provider: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: ../models/TokenRequestDto.yaml
        description: |
          application/x-www-form-urlencoded:
  /oidc/logout:
    get:
      tags:
        - token-controller
      operationId: logout
      parameters:
        - name: id_token_hint
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: default response
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '401':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '403':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
      description: Ручка выхода пользователя
components:
  schemas:
    ErrorDto:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
        additional_properties:
          type: object
          additionalProperties:
            type: string
    TokenDto:
      type: object
      properties:
        scope:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        id_token:
          type: string
  securitySchemes:
    service-provider:
      type: http
      scheme: basic
      description: Авторизация сервис провайдера
tags:
  - name: token-controller
